//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIEN_THE_SP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BIEN_THE_SP()
        {
            this.CT_HOA_DON = new HashSet<CT_HOA_DON>();
            this.CT_PHIEU_NHAP = new HashSet<CT_PHIEU_NHAP>();
            this.TON_KHO = new HashSet<TON_KHO>();
        }
    
        public int MaBienThe { get; set; }
        public string MaSP { get; set; }
        public string MaSize { get; set; }
        public string MaMau { get; set; }
        public string SKU { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual MAU_SAC MAU_SAC { get; set; }
        public virtual SIZE_GIAY SIZE_GIAY { get; set; }
        public virtual SAN_PHAM SAN_PHAM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOA_DON> CT_HOA_DON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEU_NHAP> CT_PHIEU_NHAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TON_KHO> TON_KHO { get; set; }
    }
}
