//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEU_NHAP
    {
        public string MaPN { get; set; }
        public int MaBienThe { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
    
        public virtual BIEN_THE_SP BIEN_THE_SP { get; set; }
        public virtual PHIEU_NHAP PHIEU_NHAP { get; set; }
    }
}
