//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOA_DON()
        {
            this.CT_HOA_DON = new HashSet<CT_HOA_DON>();
        }
    
        public string MaHD { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string MaKH { get; set; }
        public string MaTK { get; set; }
        public string MaKho { get; set; }
        public Nullable<int> MaPT { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOA_DON> CT_HOA_DON { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual KHO KHO { get; set; }
        public virtual PHUONG_THUC_TT PHUONG_THUC_TT { get; set; }
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
    }
}
