//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuGiaBan
    {
        public int MaLichSu { get; set; }
        public string MaSP { get; set; }
        public decimal GiaCu { get; set; }
        public decimal GiaMoi { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string LyDoDoiGia { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
