//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_NHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEU_NHAP()
        {
            this.CT_PHIEU_NHAP = new HashSet<CT_PHIEU_NHAP>();
        }
    
        public string MaPN { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string MaKho { get; set; }
        public string MaNSX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEU_NHAP> CT_PHIEU_NHAP { get; set; }
        public virtual KHO KHO { get; set; }
        public virtual NHA_SAN_XUAT NHA_SAN_XUAT { get; set; }
    }
}
