//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopGiay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLShopGiayEntities : DbContext
    {
        public QLShopGiayEntities()
            : base("name=QLShopGiayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANH_SP> ANH_SP { get; set; }
        public virtual DbSet<BIEN_THE_SP> BIEN_THE_SP { get; set; }
        public virtual DbSet<CT_HOA_DON> CT_HOA_DON { get; set; }
        public virtual DbSet<CT_PHIEU_NHAP> CT_PHIEU_NHAP { get; set; }
        public virtual DbSet<DON_VI_TINH> DON_VI_TINH { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<KHO> KHO { get; set; }
        public virtual DbSet<LOAI_HANG> LOAI_HANG { get; set; }
        public virtual DbSet<MAU_SAC> MAU_SAC { get; set; }
        public virtual DbSet<NHA_SAN_XUAT> NHA_SAN_XUAT { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<PHIEU_NHAP> PHIEU_NHAP { get; set; }
        public virtual DbSet<PHUONG_THUC_TT> PHUONG_THUC_TT { get; set; }
        public virtual DbSet<SAN_PHAM> SAN_PHAM { get; set; }
        public virtual DbSet<SIZE_GIAY> SIZE_GIAY { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<TON_KHO> TON_KHO { get; set; }
        public virtual DbSet<VAI_TRO> VAI_TRO { get; set; }
        public virtual DbSet<YEU_CAU_DANG_KY> YEU_CAU_DANG_KY { get; set; }
    
    }
}
