//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAN_PHAM()
        {
            this.ANH_SP = new HashSet<ANH_SP>();
            this.BIEN_THE_SP = new HashSet<BIEN_THE_SP>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string MaLoai { get; set; }
        public string MaNSX { get; set; }
        public string MaDVT { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ANH_SP> ANH_SP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIEN_THE_SP> BIEN_THE_SP { get; set; }
        public virtual DON_VI_TINH DON_VI_TINH { get; set; }
        public virtual LOAI_HANG LOAI_HANG { get; set; }
        public virtual NHA_SAN_XUAT NHA_SAN_XUAT { get; set; }
    }
}
