//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIZE_GIAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIZE_GIAY()
        {
            this.BIEN_THE_SP = new HashSet<BIEN_THE_SP>();
        }
    
        public string MaSize { get; set; }
        public string TenSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIEN_THE_SP> BIEN_THE_SP { get; set; }
    }
}
