//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopGiay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEU_CAU_DANG_KY
    {
        public int MaYeuCau { get; set; }
        public string TenDangNhap { get; set; }
        public string HoTen { get; set; }
        public byte[] MatKhau { get; set; }
        public System.Guid Salt { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
        public string Email { get; set; }
    }
}
